-- Vercel-compatible Costudio operational tables.
-- Run after 202607200001_shared_business_platform.sql.

create table if not exists public.costing_products (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  category text not null default 'other',
  cogs numeric(14,4) not null default 0,
  pricing jsonb not null default '{}'::jsonb,
  fabrics jsonb not null default '[]'::jsonb,
  trims jsonb not null default '[]'::jsonb,
  production_time jsonb not null default '{}'::jsonb,
  hourly_rate numeric(14,4) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.crm_clients (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  email text not null default '',
  phone text not null default '',
  measurements jsonb not null default '{}'::jsonb,
  preferences text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.crm_measurement_templates (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  category text not null default '',
  unit text not null default 'in' check (unit in ('cm','in')),
  fields jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.costing_materials (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  type text not null default 'fabric' check (type in ('fabric','trimming','other')),
  unit text not null default 'm',
  price_per_unit numeric(14,4) not null default 0,
  qty_in_stock numeric(14,4) not null default 0,
  source text not null default 'business' check (source in ('business','customer')),
  customer_name text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.crm_orders (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  customer_id bigint references public.crm_clients(id) on delete set null,
  product_name text not null,
  product_id bigint references public.costing_products(id) on delete set null,
  order_type text not null default 'bespoke' check (order_type in ('bespoke','stock')),
  quantity integer not null default 1 check (quantity > 0),
  price_agreed numeric(14,4) not null default 0,
  currency text not null default '$',
  status text not null default 'quote' check (status in ('quote','confirmed','in_production','ready','due_collection','collected','in_stock','sold','in_progress','delivered','cancelled')),
  payment_status text not null default 'unpaid' check (payment_status in ('unpaid','deposit','paid')),
  deposit_amount numeric(14,4) not null default 0,
  notes text not null default '',
  materials jsonb not null default '[]'::jsonb,
  ordered_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.costudio_feedback (
  business_id uuid primary key references public.businesses(id) on delete cascade,
  business_type text not null default '',
  country text not null default '',
  raised_prices boolean,
  price_increase numeric(8,2),
  impact_text text not null default '',
  consent boolean not null default false,
  updated_at timestamptz not null default now()
);

create index if not exists costing_products_business_idx on public.costing_products(business_id, created_at desc);
create index if not exists crm_clients_business_idx on public.crm_clients(business_id, name);
create index if not exists crm_orders_business_idx on public.crm_orders(business_id, ordered_at desc);
create index if not exists costing_materials_business_idx on public.costing_materials(business_id, type, name);

do $$
declare table_name text;
begin
  foreach table_name in array array['costing_products','crm_clients','crm_measurement_templates','costing_materials','crm_orders','costudio_feedback']
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists %I on public.%I', table_name || '_member_all', table_name);
    execute format(
      'create policy %I on public.%I for all using (public.is_business_member(business_id)) with check (public.is_business_member(business_id))',
      table_name || '_member_all', table_name
    );
    execute format('grant select, insert, update, delete on public.%I to authenticated', table_name);
  end loop;
end $$;

grant usage, select on all sequences in schema public to authenticated;
